### ISSUE TITLE
F0修改建议

### ISSUE THREAD

**Issue by MidaAiZ** [wxf980218/web_tasks#1]
1. 整体样式过于简单，登录表单缺乏样式，页面效果有待提升
2. 布局混乱， 记住密码/隐藏密码等标签定位有问题， 同时不应该将坐标写死，可能在你的电脑上显示正常，但是换一个分辨率的屏幕标签就乱飞了
3. 杜绝使用内联样式，尽量不要使用内部样式， 请将样式提取出来通过类名进行选择，并通过style标签引入外部样式
4. 样式表尽可能使用类名进行选择，当前使用id作为选择器会导致优先级过大不易修改样式

**Comment by wxf980218** [comment]
好的
